services:
  web:
    build: .
    ports:
      - "8090:80"
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./vendor:/var/www/html/vendor
    depends_on:
      - db
  db:
    image: mysql:9.2
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fitness_club
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - "8091:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  db_data: